module.exports = [
  {
    slug: "index",
    title: "Hüser Bruckmaier Wastl – Rechtsanwälte, Notare, Fachanwälte in Unna",
    description: "Ihr Ansprechpartner für Rechtsfragen und notarielle Tätigkeiten in Unna. Seit über 50 Jahren an Ihrer Seite.",
    navKey: "start",
    contentFile: "index.content.html",
  },
  {
    slug: "team",
    title: "Team – Hüser Bruckmaier Wastl",
    description: "Acht Berufsträger, ein Anspruch: Lernen Sie das Kanzlei-Team von Hüser Bruckmaier Wastl kennen.",
    navKey: "team",
    contentFile: "team.content.html",
  },
  {
    slug: "team/joachim-wastl",
    title: "Joachim Wastl – Hüser Bruckmaier Wastl",
    description: "Partner · Rechtsanwalt und Notar: Fachanwalt für Verkehrs- und Verwaltungsrecht.",
    navKey: "team",
    contentFile: "team/joachim-wastl.content.html",
  },
  {
    slug: "team/jens-peter-hueser",
    title: "Jens Peter Hüser – Hüser Bruckmaier Wastl",
    description: "Partner · Rechtsanwalt und Notar: Fachanwalt für Arbeitsrecht.",
    navKey: "team",
    contentFile: "team/jens-peter-hueser.content.html",
  },
  {
    slug: "team/katharina-wiegers",
    title: "Katharina Wiegers – Hüser Bruckmaier Wastl",
    description: "Partnerin · Rechtsanwältin und Notarin: Fachanwältin für Arbeits- und Familienrecht.",
    navKey: "team",
    contentFile: "team/katharina-wiegers.content.html",
  },
  {
    slug: "team/julia-kimmina",
    title: "Julia Kimmina – Hüser Bruckmaier Wastl",
    description: "Rechtsanwältin: Tätigkeitsschwerpunkt Familien- und Verwaltungsrecht.",
    navKey: "team",
    contentFile: "team/julia-kimmina.content.html",
  },
  {
    slug: "team/matthias-baumgart",
    title: "Matthias Baumgart – Hüser Bruckmaier Wastl",
    description: "Rechtsanwalt: Fachanwalt für Verkehrsrecht.",
    navKey: "team",
    contentFile: "team/matthias-baumgart.content.html",
  },
  {
    slug: "team/carola-haas",
    title: "Dr. Carola Haas – Hüser Bruckmaier Wastl",
    description: "Rechtsanwältin: Fachanwältin für Familien- und Sozialrecht.",
    navKey: "team",
    contentFile: "team/carola-haas.content.html",
  },
  {
    slug: "team/katharina-haarmann",
    title: "Katharina Haarmann – Hüser Bruckmaier Wastl",
    description: "Rechtsanwältin: Tätigkeitsschwerpunkt Verkehrsrecht.",
    navKey: "team",
    contentFile: "team/katharina-haarmann.content.html",
  },
  {
    slug: "team/samantha-heinen",
    title: "Samantha Heinen – Hüser Bruckmaier Wastl",
    description: "Rechtsanwältin: Tätigkeitsschwerpunkt Arbeitsrecht.",
    navKey: "team",
    contentFile: "team/samantha-heinen.content.html",
  },
  {
    slug: "rechtsgebiete",
    title: "Rechtsgebiete – Hüser Bruckmaier Wastl",
    description: "Recht für jede Lebenslage: unsere Rechtsgebiete im Überblick, geordnet nach Themen statt Paragrafen.",
    navKey: "rechtsgebiete",
    contentFile: "rechtsgebiete.content.html",
  },
  {
    slug: "notare",
    title: "Notare – Hüser Bruckmaier Wastl",
    description: "Notarielle Beurkundung, Immobilien, Gesellschaftsgründungen, Erbfallregelungen – unsere Notare in Unna.",
    navKey: "notare",
    contentFile: "notare.content.html",
  },
  {
    slug: "ueber-uns",
    title: "Über uns – Hüser Bruckmaier Wastl",
    description: "Seit mehr als 50 Jahren in Unna: unsere Geschichte, unsere Werte, unser Standort.",
    navKey: "ueber-uns",
    contentFile: "ueber-uns.content.html",
  },
  {
    slug: "impressum",
    title: "Impressum – Hüser Bruckmaier Wastl",
    description: "Impressum von Hüser Bruckmaier Wastl, Rechtsanwälte Notare Fachanwälte, Unna.",
    navKey: "",
    contentFile: "impressum.content.html",
  },
  {
    slug: "datenschutz",
    title: "Datenschutz – Hüser Bruckmaier Wastl",
    description: "Datenschutzerklärung von Hüser Bruckmaier Wastl.",
    navKey: "",
    contentFile: "datenschutz.content.html",
  },
];
